### PR TITLE
Fixing issue with cyplot and nodes without attributes

### PR DESCRIPTION
**Pull request by jooolia**
References issue #25 cc: @m-grimes 

Attempted to fix behaviour cyplot when nodes do not have any attributes. Only adds the attributes if there are more than 1 columns in the node table.

### CODE REVIEW

**Comment by jooolia** [comment]
Hi! The above function did not work for me with:

```
node.tbl <- data.frame(Gene.Name=c("FOX", "CENT", "RTK"))
edge.tbl <- data.frame(Gene.1=c("FOX", "FOX", "CENT", "CENT"),
                       Gene.2=c("CENT", "RTK", "FOX", "RTK"),
                       Weight=as.numeric(c(0.1, 1, 2, 0.02)),
                       edgeType="interaction")
cg <- cyPlot(node.tbl, edge.tbl)
```

Get the same: "Error in attr(nodeDataDefaults(graph, attr = attribute.name), "class") = attribute.type : 
  attempt to set an attribute on NULL" error. 

I think my pull request manages to cover the different cases. Are the "if" statements too ugly? I am open to a better way. :sweat_smile:

**Comment by m-grimes** [comment]
# Revised to include a test for attributes in both nodes and edges beyond the node name.

cyPlot <- function (node.df, edge.df) {
    edge.nodes <- unique(c(as.character(edge.df[, 1]), as.character(edge.df[, 
        2])))
    mydata <- new("graphNEL", edgemode = "directed", nodes = unique(c(as.character(node.df[, 
        1]), edge.nodes)))
    node.df[, 1] <- as.character(node.df[, 1])
    edge.df[, 1:2] <- sapply(edge.df[, 1:2], as.character)
    node.class <- sapply(node.df, class)
    if (any(grep("factor", node.class))) {
        node.df[, grep("factor", node.class)] <- sapply(node.df[, 
            grep("factor", node.class)], as.character)
    }
    if (any(grep("integer", node.class))) {
        node.df[, grep("integer", node.class)] <- sapply(node.df[, 
            grep("integer", node.class)], as.numeric)
    }
    node.class <- sapply(node.df, class)
    edge.class <- sapply(edge.df, class)
    if (any(grep("factor", edge.class))) {
        edge.df[, grep("factor", edge.class)] <- sapply(edge.df[, 
            grep("factor", edge.class)], as.character)
    }
    edge.class <- sapply(edge.df, class)
    if (dim(node.df)[2] > 2) {
    for (i in 2:length(grep("character", node.class))) {
        mydata <- initNodeAttribute(graph = mydata, attribute.name = names(node.class[grep("character", 
            node.class)])[i], attribute.type = "char", default.value = "undefined")
        nodeData(mydata, n = as.character(node.df[, 1]), attr = names(node.class[grep("character", 
            node.class)])[i]) <- as.character(node.df[, grep("character", 
            node.class)[i]])
    }
    for (i in 1:length(grep("numeric", node.class))) {
        mydata <- initNodeAttribute(graph = mydata, attribute.name = names(node.class[grep("numeric", 
            node.class)])[i], attribute.type = "numeric", default.value = 0)
        nodeData(mydata, n = as.character(node.df[, 1]), attr = names(node.class[grep("numeric", 
            node.class)])[i]) <- as.numeric(node.df[, grep("numeric", 
            node.class)[i]])
    }}
    mydata = addEdge(as.vector(edge.df[, 1], mode = "character"), 
        as.vector(edge.df[, 2], mode = "character"), mydata)
    if (dim(edge.df)[2] > 2) {
    for (i in 3:length(grep("character", edge.class))) {
        mydata <- initEdgeAttribute(graph = mydata, attribute.name = names(edge.df[, 
            grep("character", edge.class)])[i], attribute.type = "char", 
            default.value = "undefined")
        edgeData(mydata, as.vector(edge.df[, 1], mode = "character"), 
            as.vector(edge.df[, 2], mode = "character"), attr = names(edge.df[, 
                grep("character", edge.class)])[i]) <- as.character(edge.df[, 
            grep("character", edge.class)[i]])
    }
    for (i in 1:length(grep("numeric", edge.class))) {
        mydata <- initEdgeAttribute(mydata, attribute.name = names(edge.class[grep("numeric", 
            edge.class)])[i], attribute.type = "numeric", default.value = 0)
        edgeData(mydata, as.vector(edge.df[, 1], mode = "character"), 
            as.vector(edge.df[, 2], mode = "character"), attr = names(edge.class[grep("numeric", 
                edge.class)])[i]) <- as.numeric(edge.df[, grep("numeric", 
            edge.class)[i]])
            }
    }
    return(mydata)
}

**Comment by m-grimes** [comment]
Julia

I see the problem.  We need to have an 'if' statement for node.df as 
well as edge.df to test for other attributes besides gene name.  I put 
another one in the attached.  Thanks for pointing this out; I always had 
more attributes so I missed this and it's good to be able to handle 
every case.

I did try yours and for some reason didn't get it to work, probably 
typed something wrong. In any case this works now.

Thanks Jule,

Mark

---

**Mark Grimes
        Division of Biological Sciences
        University of Montana
        Missoula, Montana  59812-4824**
[Grimes lab website](http://hs.umt.edu/dbs/labs/grimes/)
        Office Telephone: (406) 243-4977
        Fax Number:  (406) 243-4184
        E-mail: Mark.Grimes@mso.umt.edu

On 28 Jun 2016, at 2:36, Julia Gustavsen wrote:

> Hi! The above function did not work for me with:
> 
> ```
> node.tbl <- data.frame(Gene.Name=c("FOX", "CENT", "RTK"))
> edge.tbl <- data.frame(Gene.1=c("FOX", "FOX", "CENT", "CENT"),
>                        Gene.2=c("CENT", "RTK", "FOX", "RTK"),
>                        Weight=as.numeric(c(0.1, 1, 2, 0.02)),
>                        edgeType="interaction")
> cg <- cyPlot(node.tbl, edge.tbl)
> ```
> 
> Get the same: "Error in attr(nodeDataDefaults(graph, attr = 
> attribute.name), "class") = attribute.type :
>   attempt to set an attribute on NULL" error.
> 
> I think my pull request manages to cover the different cases. Are the 
> "if" statements too ugly? I am open to a better way. :sweat_smile:
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/tmuetze/Bioconductor_RCy3_the_new_RCytoscape/pull/27#issuecomment-228986964

cyPlot.2 <- function (node.df, edge.df) {
    edge.nodes <- unique(c(as.character(edge.df[, 1]), as.character(edge.df[, 
        2])))
    mydata <- new("graphNEL", edgemode = "directed", nodes = unique(c(as.character(node.df[, 
        1]), edge.nodes)))
    node.df[, 1] <- as.character(node.df[, 1])
    edge.df[, 1:2] <- sapply(edge.df[, 1:2], as.character)
    node.class <- sapply(node.df, class)
    if (any(grep("factor", node.class))) {
        node.df[, grep("factor", node.class)] <- sapply(node.df[, 
            grep("factor", node.class)], as.character)
    }
    if (any(grep("integer", node.class))) {
        node.df[, grep("integer", node.class)] <- sapply(node.df[, 
            grep("integer", node.class)], as.numeric)
    }
    node.class <- sapply(node.df, class)
    edge.class <- sapply(edge.df, class)
    if (any(grep("factor", edge.class))) {
        edge.df[, grep("factor", edge.class)] <- sapply(edge.df[, 
            grep("factor", edge.class)], as.character)
    }
    edge.class <- sapply(edge.df, class)
    if (dim(node.df)[2] > 2) {
    for (i in 2:length(grep("character", node.class))) {
        mydata <- initNodeAttribute(graph = mydata, attribute.name = names(node.class[grep("character", 
            node.class)])[i], attribute.type = "char", default.value = "undefined")
        nodeData(mydata, n = as.character(node.df[, 1]), attr = names(node.class[grep("character", 
            node.class)])[i]) <- as.character(node.df[, grep("character", 
            node.class)[i]])
    }
    for (i in 1:length(grep("numeric", node.class))) {
        mydata <- initNodeAttribute(graph = mydata, attribute.name = names(node.class[grep("numeric", 
            node.class)])[i], attribute.type = "numeric", default.value = 0)
        nodeData(mydata, n = as.character(node.df[, 1]), attr = names(node.class[grep("numeric", 
            node.class)])[i]) <- as.numeric(node.df[, grep("numeric", 
            node.class)[i]])
    }}
    mydata = addEdge(as.vector(edge.df[, 1], mode = "character"), 
        as.vector(edge.df[, 2], mode = "character"), mydata)
    if (dim(edge.df)[2] > 2) {
    for (i in 3:length(grep("character", edge.class))) {
        mydata <- initEdgeAttribute(graph = mydata, attribute.name = names(edge.df[, 
            grep("character", edge.class)])[i], attribute.type = "char", 
            default.value = "undefined")
        edgeData(mydata, as.vector(edge.df[, 1], mode = "character"), 
            as.vector(edge.df[, 2], mode = "character"), attr = names(edge.df[, 
                grep("character", edge.class)])[i]) <- as.character(edge.df[, 
            grep("character", edge.class)[i]])
    }
    for (i in 1:length(grep("numeric", edge.class))) {
        mydata <- initEdgeAttribute(mydata, attribute.name = names(edge.class[grep("numeric", 
            edge.class)])[i], attribute.type = "numeric", default.value = 0)
        edgeData(mydata, as.vector(edge.df[, 1], mode = "character"), 
            as.vector(edge.df[, 2], mode = "character"), attr = names(edge.class[grep("numeric", 
                edge.class)])[i]) <- as.numeric(edge.df[, grep("numeric", 
            edge.class)[i]])
            }
    }
    return(mydata)
}

**Comment by jooolia** [comment]
Great! Will you update RCy3.R? thanks for the help!

**Comment by m-grimes** [comment]
Tanja

You are in charge of updating, will it be possible to include the 
revision of cyPlot I just uploaded?

Thanks,

Mark

---

**Mark Grimes
        Division of Biological Sciences
        University of Montana
        Missoula, Montana  59812-4824**
[Grimes lab website](http://hs.umt.edu/dbs/labs/grimes/)
        Office Telephone: (406) 243-4977
        Fax Number:  (406) 243-4184
        E-mail: Mark.Grimes@mso.umt.edu

**Comment by tmuetze** [comment]
Should we merge the branch?

**Comment by jooolia** [comment]
I will test out @m-grimes 's version and re-commit.

**Comment by jooolia** [comment]
Hi! I tested out the cyPlot.2 and it failed on 

```
node.tbl <- data.frame(Gene.Name=c("FOX", "CENT", "RTK"))
edge.tbl <- data.frame(Gene.1=c("FOX", "FOX", "CENT", "CENT"),
                       Gene.2=c("CENT", "RTK", "FOX", "RTK"),
                       Weight=as.numeric(c(0.1, 1, 2, 0.02)))
cg <- cyPlot(node.tbl, edge.tbl)
```

I have modified my  proposed version of `cyPlot()` and it works when I build the package. I think it could be merged.

**Pull request merged**
